apiVersion: v1
data:
  apiToken: ZHQwYzAxLkpTRVhRUjdJWkJDMzZaWlpTS0lXTFY2Ty5NVUlIUTRVUUgyQ080T0JGQ0xRWlhTRERKUTMySEdONEhJNFNTWFJENlNUSU9aRk5aNVZMUTU3SlFEVFFPRkJR
  dataIngestToken: ZHQwYzAxLjNQQVNDUlpMR0ZLMkFVVVFaWlFFVUpPNS5OWjRQVk1BRkJINVNFR1hIWFczUVhLM0RFWFlEWDRHTDczVEZZQkVGSkhPRzJHWEhRSlU3VTM3V1BXWjRXMk1C
kind: Secret
metadata:
  name: test-monitoring
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
type: Opaque
---
apiVersion: dynatrace.com/v1beta5
kind: DynaKube
metadata:
  name: test-monitoring
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
  annotations:
    feature.dynatrace.com/k8s-app-enabled: "true"
# Link to api reference for further information: https://docs.dynatrace.com/docs/ingest-from/setup-on-k8s/reference/dynakube-parameters
spec:
  apiUrl: https://aay35827.live.dynatrace.com/api
  trustedCAs: gehc-root-ca-certs
  networkZone: us-east2
  metadataEnrichment:
    enabled: true
  oneAgent:
    applicationMonitoring:
      namespaceSelector:
        matchLabels:
          dt-monitoring: "true"
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
      - debugging
    resources:
      requests:
        cpu: 500m
        memory: 1.5Gi
      limits:
        cpu: 1000m
        memory: 1.5Gi
  templates:
    logMonitoring:
      imageRef:
        repository: public.ecr.aws/dynatrace/dynatrace-logmodule
        tag: 1.327.56.20251218-151643
  logMonitoring: {}

